"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CharactersCollection_1 = require("./CharactersCollection");
var LinkedList_1 = require("./LinkedList");
var NumbersCollection_1 = require("./NumbersCollection");
var Sorter_1 = require("./Sorter");
var numbersCollection = new NumbersCollection_1.NumbersCollection([3, 2, 1]);
var charactersCollection = new CharactersCollection_1.CharactersCollection("test");
var sorterNumber = new Sorter_1.Sorter(numbersCollection);
sorterNumber.sort();
console.log(numbersCollection);
var sorterCharacters = new Sorter_1.Sorter(charactersCollection);
sorterCharacters.sort();
console.log(charactersCollection);
var linkedList = new LinkedList_1.LinkedList();
linkedList.add(3);
linkedList.add(2);
linkedList.add(1);
var sorterLinkedList = new Sorter_1.Sorter(linkedList);
sorterLinkedList.sort();
linkedList.print();
